Repository SoLanches/Frontend-SoLanches, pull requests merged in 2021-09, with the labels that each got.

#32 Edit product modal
  src/Components/EditModal/index.jsx
  src/Components/EditModal/styles.module.css
  src/styles/App.css
Labels: enhancement

#42 Refatora componente ProductCard
  src/Components/ProductCard/index.jsx
  src/Components/ProductCard/style.module.css
Labels: Refactor

#49 Refatorando componente CheckCategory
  src/Components/CheckCategory/index.jsx
  src/Components/CheckCategory/styles.module.css
Labels: Refactor

#48 Testes para verificação do componente CommerceInfo
  cypress/integration/components/commerce-info.spec.js
Labels: test

#47 Adiciona condição no header para caso o usuário ja esteja logado
  src/Components/Header/index.jsx
  src/contexts/pages.context.js
Labels: Refactor

#45 Adiciona componente RegisterSchedule
  src/Components/Button/index.jsx
  src/Components/Button/style.module.css
  src/Components/RegisterSchedules/index.jsx
  src/Components/RegisterSchedules/style.module.css
  src/Components/Schedule/index.jsx
  src/Components/Schedule/style.module.css
  src/pages/Categories/index.jsx
  src/styles/App.css
Labels: enhancement

#70 Test CardCommerce
  cypress/integration/components/card-commerce.spec.js
  src/assets/images/laemrobson.png
Labels: test

#71 Adiciona página de edição do cardápio
  package-lock.json
  src/App.js
  src/Components/Button/index.jsx
  src/Components/Button/style.module.css
  src/Components/CategoryTags/index.jsx
  src/Components/CategoryTags/style.module.css
  src/Components/EditModal/index.jsx
  src/Components/Header/index.jsx
  src/Components/Header/style.module.css
  src/Components/ProductCard/index.jsx
  src/Components/ProductCard/style.module.css
  src/Components/Select/index.jsx
  src/Components/Select/style.module.css
  src/assets/icons/Elipse/index.jsx
  src/assets/icons/Shopping/index.jsx
  src/assets/icons/Shopping/style.module.css
  src/assets/icons/Smile/index.jsx
  src/assets/icons/shopping.svg
  src/contexts/commerce.context.js
  src/contexts/pages.context.js
  src/pages/Categories/index.jsx
  src/pages/EditMenu/EditPage/index.jsx
  src/pages/EditMenu/EditPage/style.module.css
  src/pages/EditMenu/index.jsx
  src/services/api.js
  src/styles/App.css
  src/util/format.js
  src/util/notification.js
  yarn.lock
Labels: enhancement

#73 Documentation/luciano
  Docs.md
Labels: documentation

#62 Test ProfileImage
  cypress/integration/components/profile-image.spec.js
Labels: test

#75 Adiciona página de inicio do soLanches
  src/App.js
  src/assets/icons/Shopping.svg
  src/assets/icons/Shopping/index.jsx
  src/assets/icons/Shopping/style.module.css
  src/assets/icons/iconPadding.svg
  src/contexts/pages.context.js
  src/pages/Home/index.jsx
  src/pages/Home/style.module.css
  src/styles/App.css
Labels: enhancement

#78 Feature/categories commerces
  src/Components/CardCommerce/index.jsx
  src/Components/CardCommerce/style.module.css
  src/Components/CategoryCard/index.jsx
  src/Components/CategoryCard/style.module.css
  src/assets/images/alimento.svg
  src/assets/images/hamburguer.svg
  src/assets/images/lanche.svg
  src/assets/images/pizza.svg
  src/assets/images/sorvete.svg
  src/assets/images/user.svg
  src/contexts/categoryCommerce.context.jsx
  src/pages/Categories/CommerceCategory/index.jsx
  src/pages/Categories/CommerceCategory/style.module.css
  src/pages/Categories/categories.data.js
  src/pages/Categories/index.jsx
  src/pages/Categories/style.module.css
  src/services/api.js
  src/util/format.js
Labels: enhancement

#77 Refatora componente de header para se adaptar as mudanças feitas com relação a login
  src/App.js
  src/Components/Button/style.module.css
  src/Components/Header/index.jsx
  src/Components/Header/style.module.css
  src/Components/LoginCard/index.jsx
  src/Components/LoginCard/styles.module.css
  src/contexts/pages.context.js
  src/index.js
Labels: Refactor

#79 Páginas de Cadastro
  cypress/integration/components/product-card.spec.js
  package.json
  src/App.js
  src/Components/CheckCategory/index.jsx
  src/Components/CheckCategory/styles.module.css
  src/Components/EditModal/index.jsx
  src/Components/Header/index.jsx
  src/Components/LoginCard/styles.module.css
  src/Components/ProfileImage/index.jsx
  src/Components/Select/index.jsx
  src/assets/icons/check.svg
  src/contexts/pages.context.js
  src/contexts/register.context.js
  src/contexts/steps.context.js
  src/pages/EditMenu/EditPage/style.module.css
  src/pages/Register/Initial/index.jsx
  src/pages/Register/Initial/styles.module.css
  src/pages/Register/Logo/index.jsx
  src/pages/Register/Logo/styles.module.css
  src/pages/Register/RegisterCategory/index.jsx
  src/pages/Register/RegisterCategory/styles.module.css
  src/pages/Register/Schedule/index.jsx
  src/pages/Register/Schedule/styles.module.css
  src/pages/Register/constants.js
  src/pages/Register/index.jsx
  src/pages/Register/steps.jsx
  src/services/api.js
  src/styles/App.css
  src/util/notification.js
  yarn.lock
Labels: enhancement
